const {
  REACT_APP_SPOTIFY_CLIENT_ID,
  REACT_APP_SPOTIFY_REDIRECT_URI,
  REACT_APP_SPOTIFY_CLIENT_SECRET,
} = process.env;

const EnvironmentVariables = {
  REDIRECT_URI: REACT_APP_SPOTIFY_REDIRECT_URI,
  CLIENT_ID: REACT_APP_SPOTIFY_CLIENT_ID,
  SECRET_ID: REACT_APP_SPOTIFY_CLIENT_SECRET,
};

export default EnvironmentVariables;
